# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: Pathologist
  name: job-name-pathologist
  description: job-description-pathologist
  playTimeTracker: JobPathologist
  setPreference: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 36000 # 10 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours
  startingGear: PathologistGear
  icon: "JobIconPathologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Pathologist

- type: startingGear
  id: PathologistGear
  equipment:
    shoes: ClothingShoesBootsJackPathologist
    id: PathologistPDA
    ears: ClothingHeadsetMedicalScience
    socks: ClothingUnderwearSocksPathologist
