# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  setPreference: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 288000 # 80 hours
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  - Paramedic
  - Pathologist

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksSeniorPhysician
