# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: MedicalSurgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobMedicalSurgeon
  setPreference: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 1800 # 5 hours
  startingGear: SurgeonGear
  icon: "JobIconMedicalSurgeon"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Paramedic
  - Pathologist

- type: startingGear
  id: SurgeonGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
