# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanBotanist
  name: job-name-typan-botanist
  playTimeTracker: JobOutpostTypanBotanist
  description: Ботаник из далёкого космоса.
  startingGear: SyndicateBotanist
  icon: "JobIconOutpostTypanBotanist"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 6000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate

- type: startingGear
  id: SyndicateBotanist
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformJumpsuitOutpostTypanBotanist
    back: ClothingBackpackSyndicateFilled
    shoes: ClothingShoesColorBlack
    id: SyndiPDABotan
