# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanResearcher
  name: job-name-typan-researcher
  playTimeTracker: JobOutpostTypanResearcher
  description: Исследователь из далёкого космоса.
  startingGear: SyndicateResearcher
  icon: "JobIconSyndicateResearcher"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobOutpostTypanAtmosTech
      time: 29600
    - !type:RoleTimeRequirement
      role: JobOutpostTypanMedic
      time: 25600
    - !type:RoleTimeRequirement
      role: JobOutpostTypanScience
      time: 32500
    - !type:RoleTimeRequirement
      role: JobOutpostTypanBotanist
      time: 33600
    - !type:DepartmentTimeRequirement
      department: Security
      time: 39000
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 36000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 43000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate

- type: startingGear
  id: SyndicateResearcher
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformJumpsuitRecruitSyndie
    shoes: ClothingShoesBootsOutpostTypan
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltAssaultOutpostTypan

    id: SyndiPDAResearcher
