# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanScience
  name: job-name-typan-science
  playTimeTracker: JobOutpostTypanScience
  description: Учёный из далёкого космоса.
  startingGear: SyndicateScience
  icon: "JobIconSyndicateScience"
  supervisors: job-supervisors-typan-rd
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 6000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]

- type: startingGear
  id: SyndicateScience
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformScienceOutpostTypan
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsScienceOutpostTypan
    shoes: ClothingShoesBootsCombat
    back: ClothingBackpackSyndicateFilled
    id: SyndiPDAScience
