- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Frontier

- type: gameMapPool
  id: ShipVsShip
  maps:
  - ShipVsShip

# Frontier: below are the upstream map pools.
  # - Amber
  # - Bagel
  # - Box
  # - Convex
  # - Core
  # - Elkridge
  # - Fland
  # #- Gate
  # - Loop
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Packed
  # - Plasma
  # - Reach
  # #- Train
