# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: MercenaryBase
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenaryBase
  requirements:
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 21600
    - !type:RoleTimeRequirement
      role: JobBrigmedic
      time: 21600
    - !type:RoleTimeRequirement
      role: JobSecurityCadet
      time: 21600
    - !type:OverallPlaytimeRequirement
      time: 22800
    - !type:DepartmentTimeRequirement
      department: Security
      time: 39600 #60 hrs
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconMercenary" 
  supervisors: job-supervisors-hire
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess
  access:
  - Mercenary
