# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: playTimeTracker
  id: JobMercenaryBase

- type: playTimeTracker
  id: JobVip

- type: playTimeTracker
  id: JobPathologist

- type: playTimeTracker
  id: JobSecurityPilot

- type: playTimeTracker
  id: JobSeniorSalvageSpecialist

- type: playTimeTracker
  id: JobSeniorAdministrator

- type: playTimeTracker
  id: JobMedicalSurgeon

- type: playTimeTracker
  id: JobCBURNLeader

- type: playTimeTracker
  id: JobCBURNSierraLeader

- type: playTimeTracker
  id: JobCBURNAgent

- type: playTimeTracker
  id: JobCBURNSierraAgent

- type: playTimeTracker
  id: JobERTLeaderAmber

- type: playTimeTracker
  id: JobERTLeaderRed

- type: playTimeTracker
  id: JobERTLeaderGamma

- type: playTimeTracker
  id: JobERTMedicalAmber

- type: playTimeTracker
  id: JobERTMedicalRed

- type: playTimeTracker
  id: JobERTMedicalGamma

- type: playTimeTracker
  id: JobERTSecurityAmber

- type: playTimeTracker
  id: JobERTSecurityRed

- type: playTimeTracker
  id: JobERTSecurityGamma

- type: playTimeTracker
  id: JobOutpostTypanAtmosTech

- type: playTimeTracker
  id: JobOutpostTypanBotanist

- type: playTimeTracker
  id: JobOutpostTypanCargotech

- type: playTimeTracker
  id: JobOutpostTypanChef

- type: playTimeTracker
  id: JobOutpostTypanMedic

- type: playTimeTracker
  id: JobOutpostTypanRD

- type: playTimeTracker
  id: JobOutpostTypanScience

- type: playTimeTracker
  id: JobOutpostTypanTelecommunicationsOfficer

- type: playTimeTracker
  id: JobOutpostTypanResearcher

- type: playTimeTracker
  id: JobERTEngineerAmber

- type: playTimeTracker
  id: JobERTEngineerRed

- type: playTimeTracker
  id: JobERTEngineerGamma

- type: playTimeTracker
  id: JobERTJanitorAmber

- type: playTimeTracker
  id: JobERTJanitorRed

- type: playTimeTracker
  id: JobERTJanitorGamma

- type: playTimeTracker
  id: JobCentralCommandAdministrator

- type: playTimeTracker
  id: JobCentralCommandOperator

- type: playTimeTracker
  id: JobCentralCommandSpecialOperationsOfficer

- type: playTimeTracker
  id: JobCentralCommandOfficer

- type: playTimeTracker
  id: JobClownSponsor

- type: playTimeTracker
  id: JobBlueShieldOfficer

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker # Used as a tracker for all borgs and midround borging.
  id: JobBorgSecurity
