# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: BorgSecurity
  name: job-name-borg-security
  description: job-description-borg-security
  playTimeTracker: JobBorgSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 # 60 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 54000 # 15 hours
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-security-borg
  jobEntity: PlayerBorgChassisSecurity
